#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: user
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwrlKr/0Rs0/SMK14ZWSRMkLTc6TxN5XJKIOCLRGXsp pf@Mac-mini.corp.hosit.ru
runcmd: []